### ISSUE TITLE
battery info not showing anymore

### ISSUE THREAD

**Issue by ik2wxx** [MattCheetham/zeddy-support#10]
Hello, vehicle battery info is no longer downloaded.
I had same problem with Renault API.
You have to delete all the x-kamereon-authorization field from the requests header (all of them).
The token is no longer required and the request of a token will reply with an error so the download process is locked.
Hope this helps.
Roberto

**Comment by MattCheetham** [comment]
I submitted build version 2.1.1 (18) to the App Store to fix this issue earlier today. The fix will be available once Apple approves the update. Thank you for flagging.
