### ISSUE TITLE
Charge history disappears

### ISSUE THREAD

**Issue by RiotCop** [MattCheetham/zeddy-support#13]
For my Zoe R90 the charge history in Zeddy disappears after a couple of days

**Comment by Dave-09** [comment]
Zeddy cannot do anything about that :( this information comes from Renault and Renault remove it after a couple of days.

So this is not a bug.

**Comment by RiotCop** [comment]
Ok, then how about a feature request? Save the information about charges locally and ideally sync it across devices via iCloud. That would be great. You already have the built in calendar, why not put it to good use?

**Comment by Dave-09** [comment]
That's a good idea! i'm not the developer :) so can't arrange that.

**Comment by RiotCop** [comment]
I guess the developer will read it

**Comment by MattCheetham** [comment]
@RiotCop Unfortunately charge history is an unofficial feature and is deleted by Renault after a few days. At this time I have no plans to start manually saving/archiving data away from Renault's services, especially given that this feature is not supported at all on the Z.E50 and may go away at any time.
