### ISSUE TITLE
Turn on SMS for Renault ZOE. Does that also work via the API and thus for Zeddy?

### ISSUE THREAD

**Issue by Dave-09** [MattCheetham/zeddy-support#15]
Hello,

I thought it would be useful if you can set via Zeddy which SMS messages you want to receive from Renault. The My Renault app is of course included :) I was wondering if Zeddy can do this too? for example I find [https://github.com/edent/Renault-Zoe-API] but I think this is the old API?

Thank you!

**Comment by ik2wxx** [comment]
Hi
I don't want to be in the way, but I tried to deepen the discussion, and found that these api (current version) are not working. 
The public available informations about this service are probably out of date OR the service just don't work, like others do, as we know, and without explanation.
Like to heard what Matt will reply.
Roberto

**Comment by Dave-09** [comment]
Thank you for your response! :) I am indeed curious if this is still possible to add via the current API.

**Comment by MattCheetham** [comment]
It does look like the current My Renault app has these settings, however, I would need information on what that API endpoint looks like to be able to even look at building this in.

I'll be honest, this isn't really the kind of thing I had in mind for Zeddy so it is pretty low priority. I would enable the setting in the My Renault app as I don't imagine many people regularly turn the setting on and off. Going to close for now.
