### ISSUE TITLE
Support Twingo ZE

### ISSUE THREAD

**Issue by bjkrebs** [MattCheetham/zeddy-support#19]
Hey... will the new Twingo ZE supported by zeddy? I hope so cause it seems almost to be the same software.

**Describe the feature**
Explain what feature you would like to see in Zeddy

**Comment by MattCheetham** [comment]
@bjkrebs  Hey, In theory, Zeddy should be able to support any Z.E. vehicle but as I don't have that vehicle to test with, I can't confirm. If you do try to use the app with the new Twingo and it doesn't work, please re-open this ticket and we can investigate and gather data.

**Comment by bjkrebs** [comment]
Hey... I will check zeddy with my Twingo when it's delivered in December
and I will let you know if it works!
Thanks for your support

Matt Cheetham <notifications@github.com> schrieb am Di. 17. Nov. 2020 um
11:36:

**Comment by bjkrebs** [comment]
Hey Matt,

I have tested Zeddy for several days now and it‘s working with my Twingo
ZE! Best Feature: I can use preheating with my Apple Watch,nice and nerdy🙈
Only thing that's not working: the temperature of the battery, it's always
20 degrees Celsius. Is there an easy way to change that?

Best wishes for next year and keep up the excellent work,

Björn

Björn Krebs <bj.krebs@gmx.de> schrieb am Di. 17. Nov. 2020 um 14:23:

**Comment by bjkrebs** [comment]
----------------------------------
Below is the data Zeddy uses from your account to power the app. By sending
this data to support you agree that we may view it to help diagnose your
issue. Your password is not in this data and will never be seen by the
Zeddy developer
----------------------------------
Auth log:
2020-12-29 14:15:38 +0000
{
"callId" : "fe83f4a4d68749fe9147f2f912f76750",
"ignoredFields" : "",
"statusCode" : 200,
"statusReason" : "OK",
"time" : "2020-12-29T14:15:38.049Z",
"apiVersion" : 2,
"id_token" :
"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJFUTBNVVE1TjBOQ1JUSkVNemszTTBVMVJrTkRRMFUwUTBNMVJFRkJSamhETWpkRU5VRkJRZyIsImtleWlkIjoiUkVRME1VUTVOME5DUlRKRU16azNNMFUxUmtORFEwVTBRME0xUkVGQlJqaERNamRFTlVGQlFnIn0.eyJpc3MiOiJodHRwczovL2ZpZG0uZ2lneWEuY29tL2p3dC8zXzRMS2JDY01NY3ZqRG0zWDg5TFU0ejRtTktZS2RsX1cwb0Q5dy1KdmloMjFXcWdKS3RGWkFuYjlZZFVnV1Q5X2EvIiwiYXBpS2V5IjoiM180TEtiQ2NNTWN2akRtM1g4OUxVNHo0bU5LWUtkbF9XMG9EOXctSnZpaDIxV3FnSkt0RlpBbmI5WWRVZ1dUOV9hIiwiaWF0IjoxNjA5MjUxMzM4LCJleHAiOjE2MDkyNTIyMzgsInN1YiI6ImRjODQ1ODNiNDMxMTQyN2I5MzljMTdkNTFjMmU0ODA0IiwiZGF0YS5wZXJzb25JZCI6IjdkMjZiODU0LTI3ZTgtNDViMS05YzhiLTAyYmNkZWYyMjY0NyIsImRhdGEuZ2lneWFEYXRhQ2VudGVyIjoiZXUxLmdpZ3lhLmNvbSJ9.bNijFNapwh-HmvWY9EUSy5TUtP976cfdnR9xLNAJak6lhs8vivHMVRAHeTSOOHNhME10v-QhTDHPmRxVeBXyIvvuVPqsqjngucMfCQ0lK-NZFlRCZMvY6UjXarKou4x3xweamKygFJCvmUPwGUiBrAruPmgtVemxy5FWrgS2OP6JHyP1W53JS-lzyh-kWtnPut8LPauBgbE3X1nb2pe6KUA9Igh0U91zoVJ9XfTIA11YKgmS8sVjRhUnd8DYLV3wyB75yxqT_lCZ5_TSS0u530DJrBYEOizK_UDduk5QPjlukOaqu0ocxdjSJ3WJSIfNfDqoTxUFQQAIVYWsrVAZig",
"errorCode" : 0
}

2020-12-29 14:15:38 +0000
{
"messages" : [
{
"message" : "The access is unauthorized",
"code" : "err.func.wired.service.person"
}
],
"errors" : [
{
"errorMessage" : "The access is unauthorized",
"errorCode" : "err.func.wired.service.person"
}
],
"type" : "FUNCTIONAL",
"error_reference" : "FUNCTIONAL"
}



Data Log:
2020-12-29 14:21:48 +0000
{
"messages" : [
{
"message" :
"{\"errors\":[{\"status\":\"403\",\"code\":\"403011\",\"title\":\"Operation
not supported\",\"detail\":\"Operation not supported for this can
(T4VS)\"}]}",
"code" : "err.func.403"
}
],
"errors" : [
{
"errorMessage" :
"{\"errors\":[{\"status\":\"403\",\"code\":\"403011\",\"title\":\"Operation
not supported\",\"detail\":\"Operation not supported for this can
(T4VS)\"}]}",
"errorCode" : "err.func.403"
}
],
"type" : "FUNCTIONAL",
"error_reference" : "FUNCTIONAL"
}

2020-12-29 14:21:48 +0000
{
"messages" : [
{
"message" :
"{\"errors\":[{\"status\":\"502\",\"code\":\"gateway.processing\",\"title\":\"VNEXT\",\"detail\":\"an
internal error occured while processing request : 403 FORBIDDEN\"}]}",
"code" : "err.tech.502"
}
],
"errors" : [
{
"errorMessage" :
"{\"errors\":[{\"status\":\"502\",\"code\":\"gateway.processing\",\"title\":\"VNEXT\",\"detail\":\"an
internal error occured while processing request : 403 FORBIDDEN\"}]}",
"errorCode" : "err.tech.502"
}
],
"type" : "TECHNICAL",
"error_reference" : "TECHNICAL"
}

2020-12-29 14:21:48 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"calendar" : {
"monday" : [

],
"friday" : [

],
"sunday" : [

],
"tuesday" : [

],
"thursday" : [

],
"wednesday" : [

],
"saturday" : [

]
}
}
}
}

2020-12-29 14:21:48 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"chargeMode" : "always"
}
}
}

2020-12-29 14:21:48 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"gpsLongitude" : 9.6409683333333298,
"lastUpdateTime" : "2020-12-29T12:07:34Z",
"gpsLatitude" : 50.6014972222222
}
}
}

2020-12-29 14:21:49 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"totalMileage" : 520.10000000000002
}
}
}

2020-12-29 14:21:49 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"batteryAvailableEnergy" : 10,
"chargingInstantaneousPower" : 12.6,
"chargingStatus" : 0,
"batteryTemperature" : 20,
"batteryAutonomy" : 67,
"chargingRemainingTime" : 50,
"plugStatus" : 0,
"timestamp" : "2020-12-29T12:15:25Z",
"batteryLevel" : 47,
"batteryCapacity" : 0
}
}
}

2020-12-29 14:21:50 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"chargeSummaries" : [
{
"month" : "202012",
"totalChargesNumber" : 6,
"totalChargesDuration" : 77
}
]
}
}
}

2020-12-29 14:21:50 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"charges" : [
{
"chargeStartDate" : "2020-12-29T11:29:36Z",
"chargeEndBatteryLevel" : 55,
"chargeEndStatus" : "ok",
"chargeEndInstantaneousPower" : 12,
"chargeEndDate" : "2020-12-29T11:50:47Z",
"chargeStartBatteryLevel" : 27,
"chargeDuration" : 22
},
{
"chargeStartDate" : "2020-12-29T11:51:53Z",
"chargeEndBatteryLevel" : 56,
"chargeEndStatus" : "ok",
"chargeEndInstantaneousPower" : 12,
"chargeEndDate" : "2020-12-29T11:53:13Z",
"chargeStartBatteryLevel" : 55,
"chargeDuration" : 2
}
]
}
}
}

Vehicles:
[
{
"vin" : "VF1AH000366314646",
"vehicleDetails" : {
"assets" : [
{
"assetType" : "PICTURE",
"renditions" : [
{
"url" : "https:\/\/3dv2.renault.com
\/ImageFromBookmark?configuration=SDLIGM%2FAVSVEL%2FRAGAC2%2FCOIN02%2FSKTPOU%2FSRGTLU%2FSSPREM%2FELCTRI%2FSSTOST%2FSECAMH%2FSRGPDB%2FPERB19%2FSPERTN%2FPERP18%2FPERS02%2FSDCOLS%2FX07%2FB07%2FEA3%2FELEC%2FDG%2FRV%2FCAREG1%2FTN%2FVSTLAR%2FRET01%2FSPROJA%2FRALU16%2FTICU11%2FATAR%2FSGAV02%2FTEQNY%2FKM%2FVERCAP%2FRDAR02%2FALEVA%2FVLCUIR%2FRETC%2FLVCIPE%2FSGACHA%2FAPL03%2FBECQA1%2FPLAT02%2FVOLRH%2FALOUCP%2FSSNAV%2FNA437%2FBVEL%2FSPREST%2FSRANAR%2FRDIF28%2FENPH02%2FSACSRA%2FSANACF%2FTLRP09%2FCHC03%2FPRUPT1%2FIMAF&databaseId=b43ab41f-7f61-4f96-94d7-2a58c2dd7d44&bookmarkSet=RSITE&bookmark=EXT_34_DESSUS&profile=HELIOS_OWNERSERVICES_LARGE",
"resolutionType" : "ONE_MYRENAULT_LARGE"
},
{
"url" : "https:\/\/3dv2.renault.com
\/ImageFromBookmark?configuration=SDLIGM%2FAVSVEL%2FRAGAC2%2FCOIN02%2FSKTPOU%2FSRGTLU%2FSSPREM%2FELCTRI%2FSSTOST%2FSECAMH%2FSRGPDB%2FPERB19%2FSPERTN%2FPERP18%2FPERS02%2FSDCOLS%2FX07%2FB07%2FEA3%2FELEC%2FDG%2FRV%2FCAREG1%2FTN%2FVSTLAR%2FRET01%2FSPROJA%2FRALU16%2FTICU11%2FATAR%2FSGAV02%2FTEQNY%2FKM%2FVERCAP%2FRDAR02%2FALEVA%2FVLCUIR%2FRETC%2FLVCIPE%2FSGACHA%2FAPL03%2FBECQA1%2FPLAT02%2FVOLRH%2FALOUCP%2FSSNAV%2FNA437%2FBVEL%2FSPREST%2FSRANAR%2FRDIF28%2FENPH02%2FSACSRA%2FSANACF%2FTLRP09%2FCHC03%2FPRUPT1%2FIMAF&databaseId=b43ab41f-7f61-4f96-94d7-2a58c2dd7d44&bookmarkSet=RSITE&bookmark=EXT_34_DESSUS&profile=HELIOS_OWNERSERVICES_SMALL_V2",
"resolutionType" : "ONE_MYRENAULT_SMALL"
}
]
}
],
"model" : {
"label" : "TWINGO III"
},
"registrationNumber" : ""
}
}
]




----------------------------------
Below is the data Zeddy uses from your account to power the app. By sending
this data to support you agree that we may view it to help diagnose your
issue. Your password is not in this data and will never be seen by the
Zeddy developer
----------------------------------
Auth log:
2020-12-29 14:15:38 +0000
{
"callId" : "fe83f4a4d68749fe9147f2f912f76750",
"ignoredFields" : "",
"statusCode" : 200,
"statusReason" : "OK",
"time" : "2020-12-29T14:15:38.049Z",
"apiVersion" : 2,
"id_token" :
"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlJFUTBNVVE1TjBOQ1JUSkVNemszTTBVMVJrTkRRMFUwUTBNMVJFRkJSamhETWpkRU5VRkJRZyIsImtleWlkIjoiUkVRME1VUTVOME5DUlRKRU16azNNMFUxUmtORFEwVTBRME0xUkVGQlJqaERNamRFTlVGQlFnIn0.eyJpc3MiOiJodHRwczovL2ZpZG0uZ2lneWEuY29tL2p3dC8zXzRMS2JDY01NY3ZqRG0zWDg5TFU0ejRtTktZS2RsX1cwb0Q5dy1KdmloMjFXcWdKS3RGWkFuYjlZZFVnV1Q5X2EvIiwiYXBpS2V5IjoiM180TEtiQ2NNTWN2akRtM1g4OUxVNHo0bU5LWUtkbF9XMG9EOXctSnZpaDIxV3FnSkt0RlpBbmI5WWRVZ1dUOV9hIiwiaWF0IjoxNjA5MjUxMzM4LCJleHAiOjE2MDkyNTIyMzgsInN1YiI6ImRjODQ1ODNiNDMxMTQyN2I5MzljMTdkNTFjMmU0ODA0IiwiZGF0YS5wZXJzb25JZCI6IjdkMjZiODU0LTI3ZTgtNDViMS05YzhiLTAyYmNkZWYyMjY0NyIsImRhdGEuZ2lneWFEYXRhQ2VudGVyIjoiZXUxLmdpZ3lhLmNvbSJ9.bNijFNapwh-HmvWY9EUSy5TUtP976cfdnR9xLNAJak6lhs8vivHMVRAHeTSOOHNhME10v-QhTDHPmRxVeBXyIvvuVPqsqjngucMfCQ0lK-NZFlRCZMvY6UjXarKou4x3xweamKygFJCvmUPwGUiBrAruPmgtVemxy5FWrgS2OP6JHyP1W53JS-lzyh-kWtnPut8LPauBgbE3X1nb2pe6KUA9Igh0U91zoVJ9XfTIA11YKgmS8sVjRhUnd8DYLV3wyB75yxqT_lCZ5_TSS0u530DJrBYEOizK_UDduk5QPjlukOaqu0ocxdjSJ3WJSIfNfDqoTxUFQQAIVYWsrVAZig",
"errorCode" : 0
}

2020-12-29 14:15:38 +0000
{
"messages" : [
{
"message" : "The access is unauthorized",
"code" : "err.func.wired.service.person"
}
],
"errors" : [
{
"errorMessage" : "The access is unauthorized",
"errorCode" : "err.func.wired.service.person"
}
],
"type" : "FUNCTIONAL",
"error_reference" : "FUNCTIONAL"
}



Data Log:
2020-12-29 14:21:48 +0000
{
"messages" : [
{
"message" :
"{\"errors\":[{\"status\":\"403\",\"code\":\"403011\",\"title\":\"Operation
not supported\",\"detail\":\"Operation not supported for this can
(T4VS)\"}]}",
"code" : "err.func.403"
}
],
"errors" : [
{
"errorMessage" :
"{\"errors\":[{\"status\":\"403\",\"code\":\"403011\",\"title\":\"Operation
not supported\",\"detail\":\"Operation not supported for this can
(T4VS)\"}]}",
"errorCode" : "err.func.403"
}
],
"type" : "FUNCTIONAL",
"error_reference" : "FUNCTIONAL"
}

2020-12-29 14:21:48 +0000
{
"messages" : [
{
"message" :
"{\"errors\":[{\"status\":\"502\",\"code\":\"gateway.processing\",\"title\":\"VNEXT\",\"detail\":\"an
internal error occured while processing request : 403 FORBIDDEN\"}]}",
"code" : "err.tech.502"
}
],
"errors" : [
{
"errorMessage" :
"{\"errors\":[{\"status\":\"502\",\"code\":\"gateway.processing\",\"title\":\"VNEXT\",\"detail\":\"an
internal error occured while processing request : 403 FORBIDDEN\"}]}",
"errorCode" : "err.tech.502"
}
],
"type" : "TECHNICAL",
"error_reference" : "TECHNICAL"
}

2020-12-29 14:21:48 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"calendar" : {
"monday" : [

],
"friday" : [

],
"sunday" : [

],
"tuesday" : [

],
"thursday" : [

],
"wednesday" : [

],
"saturday" : [

]
}
}
}
}

2020-12-29 14:21:48 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"chargeMode" : "always"
}
}
}

2020-12-29 14:21:48 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"gpsLongitude" : 9.6409683333333298,
"lastUpdateTime" : "2020-12-29T12:07:34Z",
"gpsLatitude" : 50.6014972222222
}
}
}

2020-12-29 14:21:49 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"totalMileage" : 520.10000000000002
}
}
}

2020-12-29 14:21:49 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"batteryAvailableEnergy" : 10,
"chargingInstantaneousPower" : 12.6,
"chargingStatus" : 0,
"batteryTemperature" : 20,
"batteryAutonomy" : 67,
"chargingRemainingTime" : 50,
"plugStatus" : 0,
"timestamp" : "2020-12-29T12:15:25Z",
"batteryLevel" : 47,
"batteryCapacity" : 0
}
}
}

2020-12-29 14:21:50 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"chargeSummaries" : [
{
"month" : "202012",
"totalChargesNumber" : 6,
"totalChargesDuration" : 77
}
]
}
}
}

2020-12-29 14:21:50 +0000
{
"data" : {
"type" : "Car",
"id" : "VF1AH000366314646",
"attributes" : {
"charges" : [
{
"chargeStartDate" : "2020-12-29T11:29:36Z",
"chargeEndBatteryLevel" : 55,
"chargeEndStatus" : "ok",
"chargeEndInstantaneousPower" : 12,
"chargeEndDate" : "2020-12-29T11:50:47Z",
"chargeStartBatteryLevel" : 27,
"chargeDuration" : 22
},
{
"chargeStartDate" : "2020-12-29T11:51:53Z",
"chargeEndBatteryLevel" : 56,
"chargeEndStatus" : "ok",
"chargeEndInstantaneousPower" : 12,
"chargeEndDate" : "2020-12-29T11:53:13Z",
"chargeStartBatteryLevel" : 55,
"chargeDuration" : 2
}
]
}
}
}

Vehicles:
[
{
"vin" : "VF1AH000366314646",
"vehicleDetails" : {
"assets" : [
{
"assetType" : "PICTURE",
"renditions" : [
{
"url" : "https:\/\/3dv2.renault.com
\/ImageFromBookmark?configuration=SDLIGM%2FAVSVEL%2FRAGAC2%2FCOIN02%2FSKTPOU%2FSRGTLU%2FSSPREM%2FELCTRI%2FSSTOST%2FSECAMH%2FSRGPDB%2FPERB19%2FSPERTN%2FPERP18%2FPERS02%2FSDCOLS%2FX07%2FB07%2FEA3%2FELEC%2FDG%2FRV%2FCAREG1%2FTN%2FVSTLAR%2FRET01%2FSPROJA%2FRALU16%2FTICU11%2FATAR%2FSGAV02%2FTEQNY%2FKM%2FVERCAP%2FRDAR02%2FALEVA%2FVLCUIR%2FRETC%2FLVCIPE%2FSGACHA%2FAPL03%2FBECQA1%2FPLAT02%2FVOLRH%2FALOUCP%2FSSNAV%2FNA437%2FBVEL%2FSPREST%2FSRANAR%2FRDIF28%2FENPH02%2FSACSRA%2FSANACF%2FTLRP09%2FCHC03%2FPRUPT1%2FIMAF&databaseId=b43ab41f-7f61-4f96-94d7-2a58c2dd7d44&bookmarkSet=RSITE&bookmark=EXT_34_DESSUS&profile=HELIOS_OWNERSERVICES_LARGE",
"resolutionType" : "ONE_MYRENAULT_LARGE"
},
{
"url" : "https:\/\/3dv2.renault.com
\/ImageFromBookmark?configuration=SDLIGM%2FAVSVEL%2FRAGAC2%2FCOIN02%2FSKTPOU%2FSRGTLU%2FSSPREM%2FELCTRI%2FSSTOST%2FSECAMH%2FSRGPDB%2FPERB19%2FSPERTN%2FPERP18%2FPERS02%2FSDCOLS%2FX07%2FB07%2FEA3%2FELEC%2FDG%2FRV%2FCAREG1%2FTN%2FVSTLAR%2FRET01%2FSPROJA%2FRALU16%2FTICU11%2FATAR%2FSGAV02%2FTEQNY%2FKM%2FVERCAP%2FRDAR02%2FALEVA%2FVLCUIR%2FRETC%2FLVCIPE%2FSGACHA%2FAPL03%2FBECQA1%2FPLAT02%2FVOLRH%2FALOUCP%2FSSNAV%2FNA437%2FBVEL%2FSPREST%2FSRANAR%2FRDIF28%2FENPH02%2FSACSRA%2FSANACF%2FTLRP09%2FCHC03%2FPRUPT1%2FIMAF&databaseId=b43ab41f-7f61-4f96-94d7-2a58c2dd7d44&bookmarkSet=RSITE&bookmark=EXT_34_DESSUS&profile=HELIOS_OWNERSERVICES_SMALL_V2",
"resolutionType" : "ONE_MYRENAULT_SMALL"
}
]
}
],
"model" : {
"label" : "TWINGO III"
},
"registrationNumber" : ""
}
}
]
