### ISSUE TITLE
Unable to log in when password contains special characters

### ISSUE THREAD

**Issue by MattCheetham** [MattCheetham/zeddy-support#2]
**Describe the bug**
Users with special characters in their password are unable to log into Zeddy.

**To Reproduce**
1. Set your MyRenault password to contain a special character such as `&`
2. Try to log in to Zeddy
3. See error message saying your username or password is incorrect

**iOS version**: iOS 13.5.1
**Zeddy version**: 2.1 (17)
**iOS device**: iPhone 11 Pro
**Reproducible:** Every time

**Expected behavior**
Be able to log in with a password containing special characters

**Screenshots**
![image](https://user-images.githubusercontent.com/599289/85266252-85f2be80-b46b-11ea-9225-ba525c5ddc39.png)

**Additional context**
Logs:

```
2020-06-22 08:33:54 +0000
{
  "callId" : "706b29f3a37b4d33bbdb8b22d84de17e",
  "statusCode" : 403,
  "statusReason" : "Forbidden",
  "errorMessage" : "Invalid LoginID",
  "time" : "2020-06-22T08:33:54.174Z",
  "apiVersion" : 2,
  "errorDetails" : "invalid loginID or password",
  "errorCode" : 403042
}
```

**Comment by Dave-09** [comment]
Do you have any idea when this bug will be fixed?

**Comment by MattCheetham** [comment]
Fixed in the latest build. Please let me know if you still cannot use some passwords.
