### ISSUE TITLE
Charges Not Showing

### ISSUE THREAD

**Issue by MiguelCastro1982** [MattCheetham/zeddy-support#20]
When I click on the "Charges" button it doesn't show anything on te charges for the current or previous months.
![IMG_3934](https://user-images.githubusercontent.com/74984334/100135659-ddb1ad80-2e81-11eb-9ed0-9732c3c0a66e.PNG)

**iOS version: 14.2
**Zeddy version**: 2.1.1 (18)
**iOS device: iPhone 7 Plus
**Reproducible: Happens all the time

**Comment by MattCheetham** [comment]
The charge history API is very patchy. It at most shows 7 days of history I believe and it only works on the ZE22 and ZE40, it will not and has never worked with the ZE50. I plan to hide it in a future version for newer vehicles as it's simply not supported by the manufacturer anymore.
