### ISSUE TITLE
Asking Siri for car range does not work

### ISSUE THREAD

**Issue by damukles** [MattCheetham/zeddy-support#21]
I used to ask siri for the remaining battery range. This seems not to work anymore.

Repro steps:
- Set Siri to English UK
- Ask: „How much range does my car have?“

Expected result:
Something like: „Your car‘s battery is at 55% with 200km remaining range“

Actual result:
Strangely specific answer: „Sorry, i can‘t provide information about the remaining distance in your car“.

System Information
- iPhone XR
- iOS 14.2
- Siri is active for Zeddy
- Zeddy version 2.1.1 (18)

**Comment by MattCheetham** [comment]
@damukles Asking "How much battery does my car have?" still works for me. It does seem to have disabled some phrases recently such as the one you mention. Can you try that phrase instead?

**Comment by damukles** [comment]
I can confirm Siri tries this phrase with Zeddy. However I cannot currently log in with My Renault, so I will have to come back when I figure that out.

**Comment by damukles** [comment]
It works. Thank you for sour help.
