### ISSUE TITLE
Temperature battery shows only 20 degrees celcius, no change at all

### ISSUE THREAD

**Issue by Seprila** [MattCheetham/zeddy-support#22]
**Describe the bug**

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**Zeddy version**: Version of Zeddy this bug occurred on (can be found in Zeddy's Settings tab)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Additional context**

**Comment by Dave-09** [comment]
Hello,

Is this a ZE50? then it isn't a Zeddy bug, but a Renault bug.

**Comment by rGunti** [comment]
Can confirm this is not Zeddys fault. This is what Renault's API delivers unfortunatley.

**Comment by MattCheetham** [comment]
As mentioned by others, this is unfortunately a bug with the manufacturer and only affects ZE50 vehicles. There's not much I can do about it. I plan to hide the temperature section permanently in a future version as it's, unfortunately, something I don't have the power to fix.
