### ISSUE TITLE
Log in

### ISSUE THREAD

**Issue by remi107** [MattCheetham/zeddy-support#23]
App Version 2.1.1 iOS Version 14.2 IPhone 11: Everytime I log in (with the MY Renault App username and password) the App doesn‘t show any Information... just a blank surface

![8D0C8140-42B4-43DB-A8AB-749A7D9C9011](https://user-images.githubusercontent.com/76073858/102279795-4c87a100-3f2c-11eb-9a2c-13d05e30e8b4.jpeg)

**Comment by rGunti** [comment]
I experience the same issue from time to time. I believe it has something to do with the car not being reachable. The Renault API sometimes doesn't deliver data.

**Comment by MattCheetham** [comment]
The API this app uses is very unreliable and often fails to return any data. It usually comes back within a few hours. Unfortunately, this lies with the manufacturer and is not something I can fix.
