### ISSUE TITLE
Not connecting 

### ISSUE THREAD

**Issue by donmc123** [MattCheetham/zeddy-support#24]
Been accessing the app every day but it’s not connecting. Showing last connection over two weeks ago. Each time I log in it shows 100%, connected and not charging. Regardless of the actual state.

**Comment by Dave-09** [comment]
Does the My Renault app still work? do you still have valid subscriptions?

Here Zeddy works with ZE40 simply well.

**Comment by donmc123** [comment]
Hi Matt, 

Never thought to try the Renault app. It connects but the data shown is the same as with Zeddy. I can switch on climate. I’m assuming the problem is between the car and Renault services. Before I try and contact them, do you know of any way to reset the connection?

Don McAllister
ScreenCastsONLINE

**Comment by Dave-09** [comment]
Hello John,

I think you no longer have a valid subscription and that's why it no longer works! do you check subscriptions?

I am not matt by the way :) I am a Zeddy user.

**Comment by MattCheetham** [comment]
@donmc123 As mentioned I would check in the infotainment system in the car whether your subscriptions to the service have expired as this is commonly the cause of this sort of thing. If you do think it's all still valid then there is a fuse you can pull to reset the comms unit but I can't remember off the top of my head.

As this is not a bug with Zeddy I'm going to move it to discussions so you can continue to get help from the community.
