### ISSUE TITLE
Incorrect Charging Speed (ZE50)

### ISSUE THREAD

**Issue by HansLechner** [MattCheetham/zeddy-support#25]
**Describe the bug**
Hi, the charging Speed of my Renault Zoe r110 41kwh is schön war toi fast Max charging Speed is 50kw Bit ist often Shows also 73kw Speed at a charging Station with only 11kwh Max Power - how Van er get tge valide correct? Br Hans

**To Reproduce**

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**Zeddy version**: Version of Zeddy this bug occurred on (can be found in Zeddy's Settings tab)
**iOS device**: For example iPhone XS, iPad mini, etc.
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Additional context**

**Comment by MattCheetham** [comment]
Unfortunately, the ZE50 returns incorrect charging speeds to the API. I have searched for a pattern in the numbers that are shown to see if it can be converted but unfortunately, it does just seem to report incorrectly.

I wish I could do something to fix this, but I can't. It is a manufacturer issue.

**Comment by mountbatt** [comment]
I believe these are not the numbers of charging speed. these are the numbers of the maximum possible speeds. But its just an idea …
