### ISSUE TITLE
Renault Changed the Kamereon key

### ISSUE THREAD

**Issue by ldti** [MattCheetham/zeddy-support#26]
New key is "Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2".
Source:
https://github.com/hacf-fr/renault-api/issues/181

**Comment by MattCheetham** [comment]
@ldti Thank you for this. I'll submit a hotfix shortly to get it resolved.

**Comment by ldti** [comment]
👍 👍 

Sent from my iPad

**Comment by MattCheetham** [comment]
@ldti The new version is now available in the store that fixes this issue. Thanks again for reporting.
