### ISSUE TITLE
Cannot Login or Load Data

### ISSUE THREAD

**Issue by ik2wxx** [MattCheetham/zeddy-support#29]
Looks like they changed api key again :-(
Can't get any data of car

**Comment by MattCheetham** [comment]
Thanks @ik2wxx. Have looked into this this morning and found the issue. Just more changes on Renault's end but all fixed now. Have submitted to Apple and as soon as it is approved it will be available as an update.

**Comment by MattCheetham** [comment]
Update approved. Please check the App Store.
