### ISSUE TITLE
[Login] App is blank after logging in

### ISSUE THREAD

**Issue by MattCheetham** [MattCheetham/zeddy-support#34]
**Describe the bug**
Users who log out of Zeddy then attempt to log back in (or are signing in fresh) will be met with a blank app.

**To Reproduce**
1. Log in

**Expected behavior**
App should load data

**Screenshots**
![IMG_E0BE8FF0DF70-1](https://user-images.githubusercontent.com/599289/113989864-c380d680-9848-11eb-9515-d87b19341d52.jpeg)

**Additional context**
This is caused my the service now returning multiple accounts on login. The new one is labelled "SFDC", and I suspect it's caused by dealers entering you into their Salesforce system near the end of your PCP to attempt to get you to buy a new car.

Fixable though!

**Comment by Dan3333333** [comment]
Any ETR for the fix? Thanks

**Comment by MattCheetham** [comment]
@Dan3333333 I'm going to try and get this one done this weekend.

**Comment by Dan3333333** [comment]
Great!

**Comment by Dan3333333** [comment]
@MattCheetham app is fully working after the update. Thanks again for your efforts!

**Comment by MattCheetham** [comment]
@Dan3333333 Great to hear. 👍
