### ISSUE TITLE
New Kamereon key

### ISSUE THREAD

**Issue by Dan3333333** [MattCheetham/zeddy-support#47]
@MattCheetham please update the app with new key : YjkKtHmGfaceeuExUDKGxrLZGGvtVS0J

**Comment by MattCheetham** [comment]
Thanks, I'll get on this.

**Comment by DiLeGreen** [comment]
I want to suggest to make the key changeable by the users themselve via the settings. 

Here are the updated keys for different countrys: https://github.com/db-EV/ZoePHP/blob/main/src/api-keys.php

**Comment by BillFuggle** [comment]
Just a word of thanks for your continued support & development. Looking forward to being able to use Zeddy again when new key incorporated. Tip jar used 😀

**Comment by MattCheetham** [comment]
@BillFuggle Thank you, I appreciate the tips. I've just submitted both iOS and macOS builds for review with Apple, so I'm optimistic that they'll be available to you all in the next 24-48 hours.

**Comment by MattCheetham** [comment]
The app is now updated and should allow you all to log in. Please let me know if you have any further issue logging in.
