### ISSUE TITLE
Range map not working for me?

### ISSUE THREAD

**Issue by Dave-09** [MattCheetham/zeddy-support#5]
In the Zeddy app you have the option 'Range Map'. I click on it and the map appears with the white and blue dot on it. Otherwise I can't use it? what should this option do?

![IMG_1320](https://user-images.githubusercontent.com/49677301/85402155-79e62a00-b55b-11ea-9a68-50afb72d5b90.PNG)

iOS 13.5.1
Zeddy 2.1 (16)

Thank you!

**Comment by MattCheetham** [comment]
@Dave-09 The blue highlighted area you see in the screenshot is the potential range you can travel in your vehicle.

It looks to be working correctly.

Hope this helps

**Comment by Dave-09** [comment]
I should not hope that :) that icon is literally at the door where the ZOE now is...
