### ISSUE TITLE
Show expiration time when activating air conditioning/heating

### ISSUE THREAD

**Issue by Dave-09** [MattCheetham/zeddy-support#6]
Good morning,

I was wondering if it is not possible, just like in the My Renault app, to let a time lapse before your air conditioning/heating is switched off again? then that time decreases from 5 minutes to 0. Maybe with the 'ac-history' information? there is a 'start time'.

I hope that's possible? So we have more and more functions of My Renault in Zeddy :) I think Zeddy is functioning better anyway than My Renault. So every option that can be included is a bonus.

Thank you!

**Comment by MattCheetham** [comment]
Precondition status and history is one I've considered for a while but there are a few issues:

1) The `hvac-sessions` endpoint doesn't update immediately when you send a request
2) The `hvac-sessions` endpoint isn't available for some cars/users (Mostly ZE50 users)
3) Different generations of Zoe with different software versions pre-condition for different lengths of time. My car pre-conditions for 10 minutes but some older Zoe's without update do 5 and I've seen some users say they get 20 minutes.

I see that Renault just starts a 5-minute timer, which is incorrect for my Zoe as it runs for 10. I'm able to put an arbitrary timer in like that, but it would also be incorrect.

**Comment by Dave-09** [comment]
Hello Matt,

With my ZOE from 2019, I have no option to leave it on for more than 5 minutes. No idea which car could do that? By the way, I feel the Renault count is 'always' correct. As far as I'm concerned you enter it just like Renault does :-)

I miss this now. Then you actually have everything in it like Renault has.

**Comment by MattCheetham** [comment]
Due to the lack of available data, I'm going to decline this one. If Renault updates their endpoints to reliably report the active pre-conditioning I will revisit this but until then I'm not comfortable putting in an arbitrary figure for all vehicles as a timer.
